<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cmd</string>
	</array>
	<key>name</key>
	<string>Cmd File</string>
	<key>patterns</key>
	<array>
        <!-- nouvelle syntaxe %calllib% var=:func(param1,param2) -->
        <dict>
            <key>begin</key>
            <string>%[^%]+%\s+([^=]+)=(:\w+\()[^\)]*([)])</string>
            <key>beginCaptures</key>
            <dict>
               <key>0</key>
                <dict>
                    <key>name</key>
                    <string>meta.function.cmdfile</string>
                </dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>storage.type.cmdfile</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function.cmdfile</string>
                </dict>
               <key>3</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function.cmdfile</string>
                </dict>
            </dict>
            <key>end</key>
            <string>\s|$</string>
           </dict>
            <dict>
                <!-- commandes -->
                <key>name</key>
                <string>keyword.command.cmdfile</string>
                <key>match</key>
                <string>\b(?i:append|assoc|at|attrib|break|cacls|cd|chcp|chdir|chkdsk|chkntfs|cls|cmd|color|comp|compact|convert|copy|date|del|dir|disk(?:comp|copy|part)|doskey|driverquery|echo|endlocal|erase|fc|find(?:str)?|for(?:mat|files)|fsutil|ftype|graftabl|help|ipconfig|keyb|label|md|mkdir|mode|more|move|net(?:stat|sh)?|path|pause|ping|popd|power(?:shell|cfg)|print|prompt|pushd|rd|recover|reg(?:edit)?|ren(?:ame)?|replace|restore|rmdir|robocopy|route|runas|sc|schtasks|set|setlocal|shift|sort|start|subst|shutdown|systeminfo|time(?:out)?|title|tree|type|task(?:list|kill)|tskill|ver|verify|vol|whoami|where|winr(?:s|m)|wmic|xcopy)\b</string>
            </dict>
            <dict>
                <!-- structure logique et loop -->
                <key>name</key>
                <string>keyword.control.statement.cmdfile</string>
                <key>match</key>
                <string>\b(?i:goto|call|exit)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.control.conditional.if.cmdfile</string>
                <key>match</key>
                <string>\b(?i)if\s+(?:(not)\s+)(exist|defined|errorlevel|cmdextversion)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.control.conditional.cmdfile</string>
                <key>match</key>
                <string>\b(?i)(?:if|else)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.control.repeat.cmdfile</string>
                <key>match</key>
                <string>\b(?i)for\s+(?:/f|/r|/d|/l)?</string>
            </dict>
            <dict>
                <!-- operateur de la commande if -->
                <key>name</key>
                <string>keyword.operator.cmdfile</string>
                <key>match</key>
                <string>\b(?i:EQU|NEQ|LSS|LEQ|GTR|GEQ)\b|==</string>
            </dict>
            <dict>
                <key>match</key>
                <!--
                   le token "%~" dans une commande "rem" ou "::"
                   cause une erreur fatale (bug). si on l'utilise
                   sublime va mettre toute l'expression en subrillance
                   pour nous indiquer une erreur. 

                   dans les redirections, les handles accepter sont
                   [0-9] uniquement et ne doivent pqs etre identique dans la meme reirection, les expressions suivantes sont
                   interites:
                   43> file
                   4>&12
                   0<&44
                   32>&1
                   4>&4
                   ...etc
                -->
                <string>(?x)
                    (?i:\bREM\b|::)\s*.*%~(?=\s|$)
                     |
                    (?:
                       \d?[&gt;&lt;]&amp;\d{2,}
                        |
                       \d{2,}[&gt;&lt;]&amp;\d?
                        |
                       \d{2,}&gt;{1,2}
                    )
                </string>
                <key>name</key>
                <string>invalid.illegal.token.cmdfile</string>
            </dict>
            <dict>
                <!-- supporte 3 types de commentaire:
                       REM comment 
                       :: comment
                       %= comment =% 
                -->
                <key>name</key>
                <string>comment.inline.cmdfile</string>
                <key>match</key>
                <string>(?x)
                     (?:^
                       |
                       (?&lt;=&amp;)   
                     )
                      \s*
                      (?i: rem|:: )
                      \s+
                      .*
                    |
                     %=[^%:]*=%
                </string>
            </dict>
            <dict>
                <key>begin</key>
                <string>"</string>
                <key>endCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.string.end.cmdfile</string>
                    </dict>
                </dict>
                <key>beginCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.string.begin.cmdfile</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>string.quoted.double.cmdfile</string>
                <key>end</key>
                <string>"</string>
            </dict>
            <dict>
            <!-- variable statique systemes -->
             <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.other.cmdfile</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>constant.language.variable.cmdfile</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.other.cmdfile</string>
                        </dict>
                    </dict>
                    <key>comment</key>
                    <string>definition des variables system non dynamique</string>
                    <key>match</key>
                    <string>([!%])\b(?i:(ALLUSERSPROFILE|APPDATA|CommonProgram(?:Files(?:\(x86\))?|W6432)|COMPUTERNAME|ComSpec|FP_NO_HOST_CHECK|HOME(?:DRIVE|PATH)?|LANG|LOCALAPPDATA|LOGONSERVER|NUMBER_OF_PROCESSORS|OS|Path|PATHEXT|PROCESSOR_(?:ARCHITECTURE|IDENTIFIER|LEVEL|REVISION)|Program(?:Data|Files(?:\(x86\)|W6432))|PROMPT|PSModulePath|PUBLIC|SESSIONNAME|System(?:Drive|Root)?|TE?MP|USERDOMAIN(?:_ROAMINGPROFILE)?|USERNAME|USERPROFILE|windir))(\1)</string>
                </dict>
                <dict>
                 <!-- quelques variables dynamiques et exothiques -->   
             <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.other.cmdfile</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.function.cmdfile</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.other.cmdfile</string>
                        </dict>
                    </dict>
                    <key>comment</key>
                    <string>definition de quelques variables dynamiques</string>
                    <key>match</key>
                    <string>([!%])\b(?i:(CD|DATE|TIME|RANDOM|ERRORLEVEL|CMDEXTVERSION|CMDCMDLINE|HIGHESTNUMANODENUMBER|__cd__))(\1)</string>
                </dict>
                <dict>
                  <!-- definition des variables en géneral -->
                  <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.other.cmdfile</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>variable.language.cmdfile</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.other.cmdfile</string>
                        </dict>
                    </dict>
                    <key>comment</key>
                    <string>definition des variables defini par l'utilisateur</string>
                    <key>match</key>
                    <string>([!%])([^!%]*)(\1)</string>
                </dict>
                <dict>
                <key>name</key>
                <string>keyword.operator.pipe.cmdfile</string>
                <key>match</key>
                <string>[|]</string>
            </dict>
            <dict>
                <!-- les redirection, supporte les redirections 
                     des objects et handles...
                -->
                <key>name</key>
                <string>keyword.operator.redirect.cmdfile</string>
                <key>match</key>
               <string>(?x)
                  (?:                # redir handles/object
                     (?&lt;!\d)(\d))?
                     &gt;{1,2}
                     (?!\s*&gt;) (?:&amp;(?!\1)\d(?!\d))?
                      |
                  (?:                # redir handles/command 
                    (?&lt;!\d)(\d))?   
                    &lt;
                    (?!\s*&lt;) (?:&amp;(?!\2)\d(?!\d))?
                </string>
            </dict>
       </array>
	<key>scopeName</key>
	<string>source.cmdfile</string>
	<key>uuid</key>
	<string>16f4490f-136a-4765-ba30-ad5b5dbaed37</string>
</dict>
</plist>
